### ISSUE TITLE
 Graceful Landing typo

### ISSUE THREAD

**Issue by SirJben** [AdvancedPlugins/Skills#56]
### Describe the bug

This is the default file for this talent
```
# Graceful Landing talent
name: "Graceful Landing"
description: "Reduce fall damage by up to 50%, cooldown 15s"
icon:
  type: LEATHER_BOOTS

mana: 5

abilities:
  FALL_DAMAGE:
    cooldown: 15
    effects:
      - DECREASE_DAMAGE:<random number>15-50</random>
      - PARTICLE:BLOCK_DUST:30:0.3
      - PLAY_SOUND:BLOCK_GRASS_STEP:1:0.8
 ```
`There's a typo in this function DECREASE_DAMAGE:<random number>15-50</random>. It should be <random number>15-50</random number>.`

### How to reproduce

N/A
