### ISSUE TITLE
Bug Report: Condition Variable %has enchantment in hand of <enchant>% Not Working

### ISSUE THREAD

**Issue by JCorpse2025** [AdvancedPlugins/Skills#60]
### Describe the bug

The condition variable %has enchantment in hand of <enchant>% does not properly detect Silk Touch on pickaxes when used in a MINING trigger. Despite adding %has enchantment in hand of SILK_TOUCH% : %deny%, the player still gains experience when using a Silk Touch pickaxe.

### How to reproduce

Steps to Reproduce:
1.Configure the point-triggers:

```
point-triggers:
  points: 100
    MINING:
      conditions:
        - '%item type% contains _PICKAXE : %allow%'
        - '%has enchantment in hand of SILK_TOUCH% : %deny%' 
        - '%block type% contains ANCIENT_DEBRIS : %allow%'
```

2. Equip a pickaxe with Silk Touch.
3. Mine Ancient Debris and observe that EXP is still granted, even though the condition should deny it.

Expected Behavior:
When a player mines a block with a Silk Touch pickaxe, the condition %has enchantment in hand of SILK_TOUCH% : %deny% should prevent the player from gaining EXP.

Actual Behavior:
The condition fails to detect the Silk Touch enchantment.
Players still receive EXP when using a Silk Touch pickaxe.
