### ISSUE TITLE
Bug Report: Condition Variable %item type% contains BOW : %allow% Incorrectly Triggers with Crossbows

### ISSUE THREAD

**Issue by JCorpse2025** [AdvancedPlugins/Skills#61]
### Describe the bug

The condition variable %item type% contains BOW : %allow% is expected to only trigger when using a Bow, but it also activates with a Crossbow, which is unintended behavior.

This issue is affecting abilities and talents that should be exclusive to Bows, such as the Arrow Rain talent, which is also being triggered by Crossbows.

### How to reproduce

1. Configure the abilities:

```
abilities:
  SHOOT:
    chance: 100
    cooldown: 1
    conditions:
      - "%item type% contains BOW : %allow%" # Supposed to allow only Bows
    effects:
      - SPAWN_ARROWS @Victim
      - DO_HARM:100 @Aoe{r=6,t=players}  # Damages players
      - DO_HARM:110 @Aoe{r=6,t=mobs}  # Damages mobs (10% more)
      - PARTICLE:CRIT:15:0.3 @Victim
      - PLAY_SOUND:ENTITY_ARROW_HIT_PLAYER:1:1.5 @Attacker
  SHOOT_MOB:
    chance: 100
    cooldown: 1
    conditions:
      - "%item type% contains BOW : %allow%" # Supposed to allow only Bows
    effects:
      - SPAWN_ARROWS @Victim
      - DO_HARM:100 @Aoe{r=6,t=players}  # Damages players
      - DO_HARM:110 @Aoe{r=6,t=mobs}  # Damages mobs (10% more)
      - PARTICLE:CRIT:15:0.3 @Victim
      - PLAY_SOUND:ENTITY_ARROW_HIT_PLAYER:1:1.5 @Attacker
```

2. Equip a Crossbow instead of a Bow.
3. Fire the Crossbow, and observe that the abilities still trigger despite the condition specifying "BOW".
4. Equip a Bow and test again to confirm that both weapons trigger the ability.

Expected Behavior:
Only Bows should trigger abilities that use %item type% contains BOW : %allow%.
Crossbows should NOT trigger these abilities.

### Screenshots / Videos

![Image](https://github.com/user-attachments/assets/f435a0a2-fcf8-405c-84cf-3893a34e9c7c)
