### ISSUE TITLE
[Bug Report] SHOOT and SHOOT_MOB Triggers Not Working

### ISSUE THREAD

**Issue by JCorpse2025** [AdvancedPlugins/Skills#65]
### Describe the bug

The `SHOOT` and `SHOOT_MOB` ability triggers are **not working**. Talents that rely on these triggers do not activate when using their respective weapons (Bow, Crossbow, Trident). **No effects, particles, or sounds occur when shooting.**  

**Plugin Version:**  
AdvancedSkills v1.5.5  

**Server Version:**  
PaperMC 1.21.4 Build #190  

### How to reproduce

**Steps to Reproduce:**  
1. Install AdvancedSkills v1.5.5 on PaperMC 1.21.4 Build #190.  
2. Configure talents using `SHOOT` and `SHOOT_MOB` triggers.  
3. Attempt to use a **Trident, Crossbow, or Bow** with the configured talents.  
4. Observe that **nothing happens**—no effects are triggered.  

**Expected Behavior:**  
- `SHOOT` should activate when firing a **Bow, Crossbow, or Trident**.  
- `SHOOT_MOB` should activate when hitting a **mob** with a **Bow, Crossbow, or Trident**.  
- Effects such as **lightning, increased damage, particles, and sounds** should trigger according to the configurations.  

---

#### **Thunderbolt Talent (Trident)**
```yaml
mana: 11
abilities:
  SHOOT:
    cooldown: 1
    chance: 100
    conditions:
      - '%item type% contains TRIDENT : %allow%'
    effects:
      - LIGHTNING:true
      - PARTICLE:FLASH:10:0.5
      - PLAY_SOUND:ENTITY_LIGHTNING_BOLT_THUNDER:1:1
  SHOOT_MOB:
    cooldown: 1
    chance: 100
    conditions:
      - '%item type% contains TRIDENT : %allow%'
    effects:
      - "LIGHTNING:true @Victim"
      - PARTICLE:FLASH:10:0.5
      - PLAY_SOUND:ENTITY_LIGHTNING_BOLT_THUNDER:1:1
```

#### **Power Shot Talent (Crossbow)**
```yaml
mana: 10
abilities:
  SHOOT:
    cooldown: 1
    conditions:
      - '%item type% contains CROSSBOW : %allow%'
    effects:
      - INCREASE_DAMAGE:25
      - PARTICLE:CRIT:10:0.3
  SHOOT_MOB:
    cooldown: 1
    conditions:
      - '%item type% contains CROSSBOW : %allow%'
    effects:
      - INCREASE_DAMAGE:25
      - PARTICLE:CRIT:10:0.3
```

#### **Arrow Rain Talent (Bow)**
```yaml
mana: 14
abilities:
  SHOOT:
    chance: 100
    cooldown: 1
    conditions:
      - "%item type% contains BOW : %allow%"
    effects:
      - SPAWN_ARROWS @Victim
      - DO_HARM:100 @Aoe{r=6,t=players}
      - DO_HARM:110 @Aoe{r=6,t=mobs}
      - PARTICLE:CRIT:15:0.3 @Victim
      - PLAY_SOUND:ENTITY_ARROW_HIT_PLAYER:1:1.5 @Attacker
  SHOOT_MOB:
    chance: 100
    cooldown: 1
    conditions:
      - "%item type% contains BOW : %allow%"
    effects:
      - SPAWN_ARROWS @Victim
      - DO_HARM:100 @Aoe{r=6,t=players}
      - DO_HARM:110 @Aoe{r=6,t=mobs}
      - PARTICLE:CRIT:15:0.3 @Victim
      - PLAY_SOUND:ENTITY_ARROW_HIT_PLAYER:1:1.5 @Attacker
```

---

### **Observed Behavior:**  
- **No effects, sounds, or particles** are triggered.  
- **Abilities do not activate when using Bow, Crossbow, or Trident.**  
- No **console errors** appear related to these abilities.  

### **Additional Notes:**  
- Other abilities using different triggers (e.g., `ATTACK`, `ATTACK_MOB`) **work fine**.  
- The issue occurs across **multiple weapon types (Bow, Crossbow, Trident)**, meaning **SHOOT and SHOOT_MOB do not function properly**.  

### **Request:**  
- Please **investigate and fix** the `SHOOT` and `SHOOT_MOB` triggers.  
- If the format has changed, update the **documentation** accordingly.
